import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import { ethers } from 'ethers';
import connect from '../components/connect';
export default function Home() {
  const [account,setAccount] = useState(null);
  const [contract,setContract] = useState(null);
  const [balance,setBalance] = useState(0);
  const yeildDeposit = async()=>{
    try{
      const [add,con] =await connect();
      setAccount(add);
      setContract(con);
      const amount = document.getElementById("input").value;
      setBalance((await contract.yield_deposits(account)).toString());
      await con.depositYeild(amount,{from:add,value:ethernpms.utils.parseEther(""+amount)});
    }
    catch(err){
      alert(err.message)
    }
    
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Solarzu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <div className='flex flex-col items-center gap-6 mt-10'>
        {/* <img src ="/solarzu.png"></img> */}
        <h1 className='text-2xl'>Yield Deposit</h1>
        <input type="number" placeholder='enter amount' className="text-xl" id="input"></input>
        <button className='p-3 bg-green-300 rounded-lg' onClick={yeildDeposit}>Deposit</button>
        <h3 className='text-lg'>Deposited amount : {balance}</h3>
      </div>
    </div>
  )
}
